# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180423_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='update',
            new_name='updated',
        ),
    ]
