# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180228_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
