# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='product',
            name='pages_count',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
