# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180228_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pages_count',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
