# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180228_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
