# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pages_count',
            field=models.IntegerField(default=None, max_length=4, null=True),
        ),
    ]
