# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180228_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='genre',
            new_name='genre_book',
        ),
    ]
