# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180228_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre_book',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pages_count',
        ),
    ]
